build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-curie-imu"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-internal-libs"

install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=C:\Python36\Scripts;%PATH%
  - cmd: pip3 install -U https://github.com/platformio/platformio/archive/develop.zip
  - cmd: pio pkg install --global --platform symlink://.

test_script:
  - cmd: platformio run -d %PLATFORMIO_PROJECT_DIR%

notifications:
  - provider: Slack
    incoming_webhook:
      secure: E9H0SU0Ju7WLDvgxsV8cs3J62T3nTTX7QkEjsczN0Sto/c9hWkVfhc5gGWUkxhlD975cokHByKGJIdwYwCewqOI+7BrcT8U+nlga4Uau7J8=
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
